import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    globals: false,
    include: [
      "packages/database/src/repositories/operating-bill-account-aggregate.test.ts",
      "packages/database/src/repositories/operating-bill-cost-quality.test.ts",
      "packages/database/src/repositories/gateway-ledger-settlement-quality.test.ts",
      "packages/database/src/repositories/operating-bill-concurrency.test.ts",
      "packages/database/src/repositories/operating-bill-write-barrier.test.ts",
      "packages/database/src/repositories/monthly-operating-cost.test.ts",
      "packages/database/src/repositories/operating-bill-monthly-cost.test.ts",
      "packages/database/src/repositories/usage-quality.test.ts",
      "packages/database/src/__tests-integration__/usage-aggregate.integration.test.ts",
      "packages/database/src/__tests-integration__/usage-overview.integration.test.ts",
      "packages/database/src/__tests-integration__/pool043-model-identity-migration.test.ts",
      "packages/database/src/__tests-integration__/pool043-operating-bill-concurrency.integration.test.ts",
      "packages/database/src/__tests-integration__/pool043-operating-bill-accounts.integration.test.ts",
      "apps/control-api/src/__tests-integration__/pool043-operating-bill-accounts.test.ts",
      "apps/control-api/src/__tests-integration__/pool025-operating-bill.test.ts",
      "apps/control-api/src/__tests-integration__/w18-dashboard-usage.test.ts",
      "apps/control-api/src/__tests-integration__/w20-resource-insights.test.ts",
      "packages/provider-adapters/src/__tests__/kimi-adapter.test.ts",
      "packages/provider-adapters/src/__tests__/openai-compatible-caller.test.ts",
    ],
    exclude: ["**/node_modules/**", "**/dist/**"],
    testTimeout: 120_000,
    hookTimeout: 120_000,
    fileParallelism: false,
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "json-summary"],
      reportsDirectory: "coverage/pool043-node",
      include: [
        "packages/database/src/repositories/operating-bill-account-aggregate.ts",
        "packages/database/src/repositories/operating-bill-cost-quality.ts",
        "packages/database/src/repositories/operating-bill-account-detail.ts",
        "packages/database/src/repositories/operating-bill-account-frozen-detail.ts",
        "packages/database/src/repositories/operating-bill-account-frozen.ts",
        "packages/database/src/repositories/operating-bill-account-live-detail.ts",
        "packages/database/src/repositories/operating-bill-account-live.ts",
        "packages/database/src/repositories/operating-bill-account-repository.ts",
        "packages/database/src/repositories/operating-bill-concurrency.ts",
        "packages/database/src/repositories/operating-bill-month.ts",
        "packages/database/src/repositories/operating-bill-write-barrier.ts",
        "packages/database/src/repositories/monthly-operating-cost.ts",
        "packages/database/src/repositories/monthly-operating-summary.ts",
        "packages/database/src/repositories/operating-bill-monthly-cost.ts",
        "packages/database/src/repositories/operating-bill-opening-balance.ts",
        "packages/database/src/repositories/usage-quality.ts",
        "packages/database/src/repositories/usage-aggregate-rebuild.ts",
        "packages/database/src/repositories/usage-aggregate-repository.ts",
        "packages/database/src/repositories/usage-overview-facts.ts",
        "packages/database/src/repositories/usage-overview-repository.ts",
        "packages/database/src/repositories/gateway-ledger-settlement.ts",
        "packages/database/src/repositories/gateway-ledger-settlement-assertions.ts",
        "packages/database/src/repositories/gateway-ledger-guarded-writes.ts",
        "apps/control-api/src/operating-bills/account-routes.ts",
        "apps/control-api/src/operating-bills/opening-balance-route.ts",
        "apps/control-api/src/resource-insights/query.ts",
        "apps/control-api/src/resource-insights/routes.ts",
        "packages/provider-adapters/src/adapters/kimi-adapter.ts",
        "packages/provider-adapters/src/openai-compatible-caller.ts",
      ],
      thresholds: { statements: 95, branches: 85, functions: 90, lines: 95 },
    },
  },
});
