import { sql } from "kysely";
import { randomUUID } from "node:crypto";
import { createKysely, migrateToLatest } from "./src/index.js";
import { startPostgresContainer } from "@qianliu/testing";
import { liveLineFactCtes } from "./src/repositories/operating-bill-account-month-lines.js";

const pg = await startPostgresContainer("diag_alloc");
const db = createKysely(pg.connectionString);
await migrateToLatest(db);
const ent = randomUUID(), admin = randomUUID(), emp = randomUUID();
const prov = randomUUID(), res = randomUUID(), key = randomUUID();
await db.insertInto("enterprise").values([{ id: ent, name: "diag" }]).execute();
await db.insertInto("admin_user").values([{ id: admin, enterprise_id: ent, username: "a", password_hash: "x" }]).execute();
await db.insertInto("principal").values([{ id: emp, enterprise_id: ent, type: "EMPLOYEE", name: "e" }]).execute();
await db.insertInto("provider").values([{ id: prov, enterprise_id: ent, code: "p", name: "p", adapter_type: "openai" }]).execute();
await db.insertInto("provider_resource").values([{ id: res, enterprise_id: ent, provider_id: prov, name: "r", mode: "API", credential_type: "API_KEY" }]).execute();
await db.insertInto("principal_key").values([{ id: key, enterprise_id: ent, principal_id: emp, key_prefix: "d", key_digest: "d" }]).execute();
const at = new Date("2026-09-10T10:00:00+08:00");
const req = randomUUID();
await db.insertInto("ai_request").values({ id: req, enterprise_id: ent, principal_id: emp, principal_key_id: key, protocol: "openai", unified_model: "m", status: "SUCCEEDED", started_at: at, finished_at: new Date(at.getTime()+1000) }).execute();
const att = (await db.insertInto("upstream_attempt").values({ ai_request_id: req, enterprise_id: ent, attempt_no: 1, provider_resource_id: res, upstream_model: "m", finished_at: new Date(at.getTime()+1000), http_status: 200, response_committed: true }).returning("id").executeTakeFirstOrThrow()).id;
const usg = (await db.insertInto("usage_event").values({ ai_request_id: req, enterprise_id: ent, upstream_attempt_id: att, provider_resource_id: res, input_tokens: 100n, output_tokens: 0n, usage_quality: "PROVIDER_REPORTED", dedup_key: `d-${req}`, created_at: at }).returning("id").executeTakeFirstOrThrow()).id;
await db.insertInto("ledger_line").values({ ai_request_id: req, enterprise_id: ent, usage_event_id: usg, upstream_attempt_id: att, provider_resource_id: res, principal_id: emp, resource_mode: "API", raw_input_tokens: 100n, raw_output_tokens: 0n, raw_cache_tokens: 0n, api_cost: "1.00", usage_quality: "PROVIDER_REPORTED", created_at: at }).execute();
await sql`UPDATE ledger_line SET api_cost_currency='CNY' WHERE ai_request_id=${req}`.execute(db);
const { rows } = await sql<any>`WITH ${liveLineFactCtes(ent, "2026-09")} SELECT ledger_line_id, source_principal_id, api_cost FROM line_facts`.execute(db);
console.log("line_facts rows:", JSON.stringify(rows));
const count = await sql<any>`SELECT COUNT(*)::int AS n FROM ledger_line`.execute(db);
console.log("ledger rows:", count.rows[0].n);
await db.destroy();
await pg.stop();
