import { randomUUID } from "node:crypto";
import { sql } from "kysely";
import { createKysely, migrateToLatest } from "./src/index.js";
import { startPostgresContainer } from "@qianliu/testing";
import { hasPendingOperatingBillSettlement } from "./src/repositories/operating-bill-write-barrier.js";
const pg = await startPostgresContainer("diag2");
const db = createKysely(pg.connectionString);
await migrateToLatest(db);
const ent=randomUUID();
await db.insertInto("enterprise").values([{id:ent,name:"d"}]).execute();
console.log("empty ent pending:", await hasPendingOperatingBillSettlement(db, ent, "2026-09", new Date()));
await db.destroy(); await pg.stop();
