import { randomUUID } from "node:crypto";
import { sql } from "kysely";
import { createKysely, migrateToLatest } from "./src/index.js";
import { startPostgresContainer } from "@qianliu/testing";
import { hasPendingOperatingBillSettlement } from "./src/repositories/operating-bill-write-barrier.js";
const pg = await startPostgresContainer("diag_close");
const db = createKysely(pg.connectionString);
await migrateToLatest(db);
const ent=randomUUID(),admin=randomUUID(),emp=randomUUID(),prov=randomUUID(),res=randomUUID(),key=randomUUID();
await db.insertInto("enterprise").values([{id:ent,name:"d"}]).execute();
await db.insertInto("admin_user").values([{id:admin,enterprise_id:ent,username:"a",password_hash:"x"}]).execute();
await db.insertInto("principal").values([{id:emp,enterprise_id:ent,type:"EMPLOYEE",name:"e"}]).execute();
await db.insertInto("provider").values([{id:prov,enterprise_id:ent,code:"c",name:"c",adapter_type:"openai"}]).execute();
await db.insertInto("provider_resource").values([{id:res,enterprise_id:ent,provider_id:prov,name:"r",mode:"API",credential_type:"API_KEY"}]).execute();
await db.insertInto("principal_key").values([{id:key,enterprise_id:ent,principal_id:emp,key_prefix:"k",key_digest:"d"}]).execute();
const at = new Date("2026-09-10T02:00:00Z");
const req = randomUUID();
await db.insertInto("ai_request").values({id:req,enterprise_id:ent,principal_id:emp,principal_key_id:key,protocol:"openai",unified_model:"m",status:"SUCCEEDED",started_at:at,finished_at:new Date(at.getTime()+1000)}).execute();
const att=(await db.insertInto("upstream_attempt").values({ai_request_id:req,enterprise_id:ent,attempt_no:1,provider_resource_id:res,upstream_model:"m",finished_at:new Date(at.getTime()+1000),http_status:200,response_committed:true}).returning("id").executeTakeFirstOrThrow()).id;
const usg=(await db.insertInto("usage_event").values({ai_request_id:req,enterprise_id:ent,upstream_attempt_id:att,provider_resource_id:res,input_tokens:100n,output_tokens:0n,cache_tokens:0n,reasoning_tokens:0n,usage_quality:"PROVIDER_REPORTED",dedup_key:`d-${req}`,created_at:at}).returning("id").executeTakeFirstOrThrow()).id;
await db.insertInto("ledger_line").values({ai_request_id:req,enterprise_id:ent,usage_event_id:usg,upstream_attempt_id:att,provider_resource_id:res,principal_id:emp,resource_mode:"API",raw_input_tokens:100n,raw_output_tokens:0n,raw_cache_tokens:0n,api_cost:"1.00",usage_quality:"PROVIDER_REPORTED",created_at:at}).execute();
await sql`UPDATE ledger_line SET api_cost_currency='CNY' WHERE ai_request_id=${req}`.execute(db);
await db.insertInto("ledger_transaction").values({ai_request_id:req,enterprise_id:ent,principal_id:emp,total_input_tokens:100n,total_output_tokens:0n,total_cache_tokens:0n,total_reasoning_tokens:0n,total_deducted_quota:0n,total_api_cost:"1.00",usage_quality:"PROVIDER_REPORTED",attempt_count:1,status:"SETTLED",created_at:at}).execute();
console.log("pending:", await hasPendingOperatingBillSettlement(db, ent, "2026-09", new Date()));
// 找出哪一支为真
const checks: Array<[string, boolean]> = [];
const q = async (name: string, query: ReturnType<typeof sql>) => { const r = await query.execute(db); checks.push([name, (r.rows[0] as {ok:boolean}).ok]); };
await q("inprogress", sql`SELECT EXISTS(SELECT 1 FROM ai_request r WHERE r.enterprise_id=${ent} AND r.status='IN_PROGRESS' AND EXISTS(SELECT 1 FROM upstream_attempt a WHERE a.enterprise_id=${ent} AND a.ai_request_id=r.id)) AS ok`);
await q("usage_no_line", sql`SELECT EXISTS(SELECT 1 FROM usage_event u WHERE u.enterprise_id=${ent} AND u.created_at >= '2026-09-01T00:00:00+08:00'::timestamptz AND u.created_at < '2026-10-01T00:00:00+08:00'::timestamptz AND NOT EXISTS(SELECT 1 FROM ledger_line l WHERE l.enterprise_id=u.enterprise_id AND l.usage_event_id=u.id)) AS ok`);
await q("line_no_tx", sql`SELECT EXISTS(SELECT 1 FROM ledger_line l WHERE l.enterprise_id=${ent} AND NOT EXISTS(SELECT 1 FROM ledger_transaction t WHERE t.enterprise_id=l.enterprise_id AND t.ai_request_id=l.ai_request_id)) AS ok`);
console.log(checks);
await db.destroy(); await pg.stop();
