import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import { startPostgresContainer } from '../../../../packages/testing/src/postgres-container.js';
import { createKysely, migrateToLatest } from '../../../../packages/database/src/index.js';
import { buildControlApi } from '../../../../apps/control-api/src/server.js';
import { hashPassword } from '../../../../apps/control-api/src/auth/password.js';
const root = process.cwd();
const requireWeb = createRequire(root + '/apps/web/package.json');
const { chromium } = requireWeb('@playwright/test');
const { createServer } = await import(requireWeb.resolve('vite'));
process.env.FEATURE_DIRECTORY_IMPORT = 'true';
const pg = await startPostgresContainer('settings_i1_negative');
const db = createKysely(pg.connectionString);
const app = buildControlApi(db);
let vite: any; let browser: any;
const evidence: any = { scope: 'I1 direct negative reproduction; ephemeral PostgreSQL only', at: new Date().toISOString() };
try {
  await migrateToLatest(db);
  const ent = await db.insertInto('enterprise').values({ name: 'I1 isolated enterprise' }).returning('id').executeTakeFirstOrThrow();
  const owner = await db.insertInto('admin_user').values({ enterprise_id: ent.id, username: 'owner', display_name: 'I1 owner', password_hash: await hashPassword('I1-Settings-2026!') }).returning('id').executeTakeFirstOrThrow();
  await app.ready();
  const login = await app.inject({ method: 'POST', url: '/auth/login', payload: { username: 'owner', password: 'I1-Settings-2026!' } });
  const cookie = String(login.headers['set-cookie']).split(';')[0]!;
  const put = await app.inject({ method: 'PUT', url: '/admin-role', headers: { cookie }, payload: { expected_version: 0, name: '主体操作岗', permissions: { principals: { view: true, operate: true } } } });
  assert.equal(put.statusCode, 200);
  const created = await app.inject({ method: 'POST', url: '/admins', headers: { cookie }, payload: { username: 'custom', display_name: 'I1 custom', password: 'I1-Settings-2026!', role_code: 'CUSTOM' } });
  assert.equal(created.statusCode, 201);
  await db.updateTable('admin_user').set({ must_change_password: false }).where('id', '=', created.json().admin.id).execute();
  const customLogin = await app.inject({ method: 'POST', url: '/auth/login', payload: { username: 'custom', password: 'I1-Settings-2026!' } });
  const customCookie = String(customLogin.headers['set-cookie']).split(';')[0]!;
  evidence.directory = [];
  for (const url of ['/directory-members', '/directory-sources/WECOM', '/directory-excel-template']) {
    const custom = await app.inject({ url, headers: { cookie: customCookie } });
    const control = await app.inject({ url, headers: { cookie } });
    evidence.directory.push({ url, customStatus: custom.statusCode, superStatus: control.statusCode, customError: custom.statusCode !== 200 ? custom.json() : null });
  }
  const principal = await app.inject({ method: 'POST', url: '/principals', headers: { cookie }, payload: { name: 'I1 sample', type: 'PROJECT' } });
  assert.equal(principal.statusCode, 201);
  const disabled = await app.inject({ method: 'PATCH', url: '/principals/' + principal.json().principal.id, headers: { cookie }, payload: { status: 'DISABLED' } });
  assert.equal(disabled.statusCode, 200);
  const audit = await app.inject({ url: '/operation-logs?search=principal.disable', headers: { cookie } });
  evidence.audit = audit.json().logs.map((r: any) => ({ action: r.action, actor_source: r.actor_source, actor_name: r.actor_name, created_at: r.created_at }));
  const api = await app.listen({ host: '127.0.0.1', port: 0 });
  process.chdir(root + '/apps/web');
  vite = await createServer({ configFile: false, root: process.cwd(), plugins: [(await import(requireWeb.resolve('@vitejs/plugin-react'))).default()], server: { host: '127.0.0.1', port: 0, proxy: { '/api': { target: api, changeOrigin: true, rewrite: (p: string) => p.replace(/^\/api/, '') } } } });
  await vite.listen(); const address = vite.httpServer.address();
  browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const page = await browser.newPage();
  const errors: string[] = [];
  page.on('pageerror', (err: Error) => errors.push(err.message));
  await page.goto(`http://127.0.0.1:${address.port}/login`);
  await page.getByLabel('用户名', { exact: true }).fill('owner');
  await page.getByLabel('密码', { exact: true }).fill('I1-Settings-2026!');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.getByRole('navigation', { name: '主导航' }).waitFor();
  const browserCookies = await page.context().cookies();
  const browserCookie = browserCookies.filter((c: any) => c.name === 'qianliu_admin_session').map((c: any) => c.name + '=' + c.value).join('; ');
  const me = await app.inject({ url: '/auth/me', headers: { cookie: browserCookie } });
  const revoke = await app.inject({ method: 'DELETE', url: '/admin-sessions/' + me.json().admin.sessionId, headers: { cookie } });
  assert.equal(revoke.statusCode, 204);
  const response = await page.waitForResponse((r: any) => r.url().endsWith('/api/auth/me') && r.status() === 401, { timeout: 40000 });
  await page.waitForTimeout(1500);
  evidence.revocation = { revokedStatus: revoke.statusCode, nextPollStatus: response.status(), url: page.url(), body: (await page.locator('body').innerText()).slice(0, 2000), pageErrors: errors.slice(0, 5) };
  await page.screenshot({ path: root + '/V4/Evidence/SYSTEM-SETTINGS-V2-20260909/I1/revoked-session.png' });
  console.log(JSON.stringify(evidence, null, 2));
} finally {
  await writeFile(root + '/V4/Evidence/SYSTEM-SETTINGS-V2-20260909/I1/negative-reproduction.json', JSON.stringify(evidence, null, 2));
  await browser?.close(); await vite?.close(); await app.close(); await db.destroy(); await pg.stop();
}
