import { defineConfig } from "vitest/config";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
const root = process.cwd();
const aliases = readdirSync(path.join(root, "packages")).map(name => {
 const dir = path.join(root, "packages", name);
 return { find: JSON.parse(readFileSync(path.join(dir, "package.json"), "utf8")).name, replacement: path.join(dir, "src/index.ts") };
});
export default defineConfig({ root, resolve: { alias: aliases }, test: {
 environment: "node", include: ["apps/control-api/src/__tests-integration__/pool015-admin-lifecycle.test.ts","apps/control-api/src/__tests-integration__/pool025-operating-bill.test.ts","apps/control-api/src/__tests-integration__/w19-resource-recovery.test.ts","apps/gateway/src/__tests-integration__/w11-resource-pool.test.ts","apps/gateway/src/__tests-integration__/w12-routing.test.ts","apps/gateway/src/pipeline/upstream-error-diagnostic.test.ts","apps/worker/src/coding-plan-quota/runner.test.ts","packages/contracts/src/__tests__/contracts.test.ts","packages/database/src/__tests-integration__/billing-rule-multi-window-migration.integration.test.ts","packages/database/src/__tests-integration__/exception-center-contract.integration.test.ts","packages/database/src/__tests-integration__/operating-snapshot-subscription-period-migration.integration.test.ts","packages/database/src/__tests-integration__/pool043-model-identity-migration.test.ts","packages/database/src/__tests-integration__/pool046-zhipu-window-alias-migration.test.ts","packages/database/src/__tests-integration__/pool047-resource-monthly-budget-migration.integration.test.ts","packages/database/src/__tests-integration__/pool048-upstream-error-evidence.integration.test.ts","packages/database/src/__tests-integration__/principal-key-single-active-migration.integration.test.ts","packages/database/src/__tests-integration__/provider-finance-cutover.integration.test.ts","packages/database/src/__tests-integration__/provider-finance-ledger.integration.test.ts","packages/database/src/__tests-integration__/resource-fact-reconciliation-migration.integration.test.ts","packages/database/src/__tests-integration__/runtime-admin-migrations.integration.test.ts","packages/database/src/__tests-integration__/runtime-admin-release-rehearsal.integration.test.ts","packages/database/src/__tests-integration__/runtime-assurance-foundation.integration.test.ts","packages/database/src/__tests-integration__/w20-final-migration.integration.test.ts","packages/domain/src/__tests__/resource-lifecycle.test.ts","packages/provider-adapters/src/__tests__/openai-compatible-caller.test.ts","apps/control-api/src/__tests-integration__/w20-diagnostics-alerts.test.ts","apps/gateway/src/__tests-integration__/runtime-assurance.integration.test.ts"],
 fileParallelism: false, maxWorkers: 1, testTimeout: 120000, hookTimeout: 120000,
 coverage: { enabled: false },
} });
