import { createRequire } from "node:module";
import { mkdir } from "node:fs/promises";
import { startPostgresContainer } from "../packages/testing/src/postgres-container.js";
import { createKysely, migrateToLatest } from "../packages/database/src/index.js";
import { buildControlApi } from "../apps/control-api/src/server.js";
import { hashPassword } from "../apps/control-api/src/auth/password.js";
const requireWeb = createRequire(new URL("../apps/web/package.json", import.meta.url));
const { chromium, expect } = requireWeb("@playwright/test");
const { createServer } = await import(requireWeb.resolve("vite"));
const root = process.cwd();
const pg = await startPostgresContainer("settings_v2_e2e");
const db = createKysely(pg.connectionString);
const app = buildControlApi(db);
let vite: Awaited<ReturnType<typeof createServer>> | undefined;
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
try {
  await migrateToLatest(db);
  const ent = await db.insertInto("enterprise").values({ name: "第二版测试企业" }).returning("id").executeTakeFirstOrThrow();
  await db.insertInto("admin_user").values({ enterprise_id: ent.id, username: "owner", display_name: "测试管理员",
    password_hash: await hashPassword("Settings-E2E-2026!"), status: "ACTIVE" }).execute();
  const api = await app.listen({ host: "127.0.0.1", port: 0 });
  process.chdir(root + "/apps/web");
  vite = await createServer({ configFile: false, root: process.cwd(), plugins: [(await import(requireWeb.resolve("@vitejs/plugin-react"))).default()],
    server: { host: "127.0.0.1", port: 0, proxy: { "/api": { target: api, changeOrigin: true, rewrite: (p: string) => p.replace(/^\/api/, "") } } } });
  await vite.listen(); const addr = vite.httpServer?.address();
  if (!addr || typeof addr === "string") throw new Error("preview port unavailable");
  const url = `http://127.0.0.1:${addr.port}`;
  browser = await chromium.launch({ headless: true, channel: "chrome" });
  const page = await browser.newPage({ viewport: { width: 1500, height: 1100 } });
  const errors: string[] = []; page.on("pageerror", (e: Error) => errors.push(e.message));
  await page.goto(url + "/settings?tab=accounts&section=roles");
  await page.getByLabel("用户名", { exact: true }).fill("owner");
  await page.getByLabel("密码", { exact: true }).fill("Settings-E2E-2026!");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("heading", { name: "系统设置", exact: true })).toBeVisible();
  await page.goto(url + "/settings?tab=accounts&section=roles");
  await page.getByLabel("岗位名称").fill("研发查看岗");
  await page.getByLabel("使用主体可查看").check();
  await page.getByRole("button", { name: "保存角色与权限" }).click();
  await expect(page.getByRole("button", { name: "研发查看岗", exact: true })).toBeVisible();
  const dir = root + "/V4/Evidence/SYSTEM-SETTINGS-V2-20260909";
  await mkdir(dir, { recursive: true });
  await page.screenshot({ path: dir + "/roles.png", fullPage: true });
  await page.getByRole("button", { name: "管理员", exact: true }).click();
  await expect(page.getByText("owner（当前）")).toBeVisible();
  await page.getByLabel("管理员用户名").fill("viewer");
  await page.getByLabel("管理员显示名称").fill("查看成员");
  await page.getByLabel("管理员初始密码").fill("Settings-E2E-2026!");
  await page.getByRole("button", { name: "创建管理员" }).click();
  await expect(page.getByText("viewer", { exact: true }).last()).toBeVisible();
  await page.getByRole("button", { name: "清除明文" }).click();
  await page.getByRole("button", { name: "登录安全", exact: true }).click();
  await page.getByLabel("会话有效期").selectOption("120");
  await page.getByRole("button", { name: "保存登录策略" }).click();
  await expect(page.getByRole("button", { name: "保存登录策略" })).toBeEnabled();
  await expect(page.getByLabel("会话有效期")).toHaveValue("120");
  await page.screenshot({ path: dir + "/security.png", fullPage: true });
  await page.getByRole("button", { name: "审计日志", exact: true }).click();
  await expect(page.getByRole("button", { name: "详情" }).first()).toBeVisible();
  await page.getByRole("button", { name: "详情" }).first().click();
  await expect(page.getByRole("dialog", { name: "操作详情" })).toBeVisible();
  await page.screenshot({ path: dir + "/audit-detail.png", fullPage: true });
  await page.getByLabel("关闭详情").click();
  await page.getByRole("button", { name: "关于版本", exact: true }).click();
  await expect(page.getByRole("button", { name: "详情", exact: true })).toHaveCount(0);
  await page.screenshot({ path: dir + "/version.png", fullPage: true });
  const viewer = await browser.newContext();
  const login = await viewer.request.post(url + "/api/auth/login", { data: { username: "viewer", password: "Settings-E2E-2026!" } });
  expect(login.status()).toBe(200);
  const changed = await viewer.request.post(url + "/api/auth/change-password", { data: { current_password: "Settings-E2E-2026!", new_password: "Changed-E2E-2026!" } });
  expect(changed.status()).toBe(204);
  await viewer.request.post(url + "/api/auth/login", { data: { username: "viewer", password: "Changed-E2E-2026!" } });
  const readPage = await viewer.newPage();
  await readPage.goto(url + "/principals");
  await expect(readPage.getByRole("link", { name: "使用主体", exact: true })).toBeVisible();
  await expect(readPage.getByRole("link", { name: "厂商资源", exact: true })).toHaveCount(0);
  await expect(readPage.locator("[data-write-action]:visible")).toHaveCount(0);
  const denied = await viewer.request.post(url + "/api/principals", { data: { name: "禁止写入", type: "EMPLOYEE" } });
  expect(denied.status()).toBe(403);
  await readPage.goto(url + "/resources");
  await expect(readPage.getByRole("alert")).toContainText("没有此模块的查看权限");
  await viewer.close();
  if (errors.length) throw new Error(errors.join("\n"));
  console.log("PASS: real browser + isolated PostgreSQL login, role, accounts, security, audit, version");
} finally { await browser?.close(); await vite?.close(); await app.close(); await db.destroy(); await pg.stop(); }
